CREATE TABLE IF NOT EXISTS products(
	id UUID PRIMARY KEY DEFAULT uuidv7(),
	name VARCHAR(255) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    stock INTEGER NOT NULL CHECK(stock >= 0),
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
